############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "About"
url = "/authors/povl-filip-sonne-frederiksen"
weight = 2


[[main]]
name = "Projects"
url = "/categories/projects/"
#projects"
weight = 4

[[main]]
name = "Blog"
url = "/blog"
weight = 5

# [[main]]
# name = "Contact"
# url = "/contact"
# weight = 6


# footer menu
[[footer]]
name = "About"
url = "/authors/povl-filip-sonne-frederiksen"
weight = 1

[[footer]]
name = "Projects"
#url = "/projects"
url = "/categories/projects/"
weight = 2

[[footer]]
name = "Privacy Policy"
url = "/privacy-policy"
weight = 3
