############# German navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "Büro"
url = "about/"
weight = 2

[[main]]
name = "Projekte"
url = "projects/"
weight = 3

[[main]]
name = "Möbel"
url = "furniture/"
weight = 4

[[main]]
name = "Blog"
url = "blog/"
weight = 5

# footer menu
[[footer]]
name = "Datenschutz Erklärung"
url = "privacy-policy/"
weight = 2
